### ISSUE TITLE
minus_op and so on

### ISSUE THREAD

**Issue by dix75** [johnmcfarlane/fixed_point#224]
Removing the const reference from operator() functions in the mimus_op and other structures gives us more faster code even for complex classes.
https://godbolt.org/g/nug99B

for the add_op the best solution is that
```
struct add_op : arithmetic_op {
template<class Lhs, class Rhs>
constexpr auto operator()(Lhs lhs, const Rhs& rhs) const noexcept(noexcept(lhs += rhs)) -> decltype(lhs+rhs) {
    lhs += rhs;
    return lhs;
}
};

```

**Comment by johnmcfarlane** [comment]
Thanks for the observations. I aim to provide zero-cost abstractions but put most of my effort into ensuring the right API design so any feedback on performance is very valuable.

Your example, `cls` is a more complex than a fundamental type but it may still be pretty easy to optimize for compared to more complicated types such as, say, Boost.Multiprecision. Also, when I add the `-O3` flag, the compiler eats up all of the code in your example so it's hard to determine what really strains the optimizer. 

Also, I have not really explored using uvalues (xvalues? I loose track), i.e. `(Rhs&& rhs)`.

Regarding the technique of passing a copy as the first parameter, that's a good approach. But unfortunately, I am maintaining support for C++11 which does not allow statements which mutate state (or indeed anything that isn't a return statement). So the `lhs += rhs;` generates a compiler error.
