### ISSUE TITLE
License

### ISSUE THREAD

**Issue by sebastient** [johnmcfarlane/fixed_point#24]
There is no licensing information provided, could this please be clarified?  Thank you.

**Comment by johnmcfarlane** [comment]
This repo contains is a reference implementation of an ISO proposal and it's where I host the proposal document itself. As such, many popular licenses would not be permissive enough to cover its entire contents. (Note that the same  is true of its [previous home](https://github.com/WG21-SG14/SG14/commit/beaf80012c5a71dc98ef8f9813346c84bff76d20) in the [SG14 repository](https://github.com/WG21-SG14/SG14).)

I asked about appropriate licenses last year. Some follow-up information can be found [here](https://groups.google.com/a/isocpp.org/forum/#!searchin/sg14/$20copyright/sg14/rvS7N3I7nlk/qdIs9-cwAQAJ). The conclusion was that a very permissive license or no license at all would allow progress on the proposal so I went with the latter.

However, I welcome any use which might result in testing and feedback so if you'd like to use the library and require a specific license which is suitably permissive, then by all means suggestion one and I'll consider applying it.

**Comment by sebastient** [comment]
It seems a public domain license of the header files might be acceptable?

http://choosealicense.com/no-license/

**Comment by johnmcfarlane** [comment]
Thanks. On reflection, I think the Boost license probably makes most sense. Take a look at [this PR](https://github.com/johnmcfarlane/fixed_point/pull/25) and LMK if it looks good.

**Comment by sebastient** [comment]
Excellent, much appreciated.
