### ISSUE TITLE
Build fails with "#error This file requires compiler and library support for the ISO C++ 2011 standard."

### ISSUE THREAD

**Issue by kraiskil** [johnmcfarlane/fixed_point#243]
Building on Ubuntu 16.04, it's default gcc (5.4.0-6ubuntu1~16.04.4).
Error triggers when building _src/single_header/single_header.cpp_
No _-std=_ flag seems to be passed to c++ 

Git bisect blames commit d4ee69f436dedbda10e5eb645d6343b48c4904b1

**Comment by johnmcfarlane** [comment]
Might be addressed in #246 although this isn't intended to be a commonly used feature.

**Comment by kraiskil** [comment]
Yes indeed, with the head from #246 ,this issue is gone.
